.TH lwt 1 "2014-07-12" " " " "

\." === [ NAME ] ===============================================================
.SH NAME
lwt \- Lightweight terminal

\." === [ SYNOPSIS ] ===========================================================
.SH SYNOPSIS
.B lwt

\." === [ DESCRIPTION ] ========================================================
.SH DESCRIPTION
A lightweight terminal emulator based on
the
.B
GTK
and
.B
VTE
libraries.

\." === [ KEY BINDINGS ] =======================================================
.
.SH "KEY BINDINGS"
The default key bindings of VTE are extended with the following:
.IP "\fB[ctrl]-[shift]-c\fP  Copy selection."
.IP "\fB[ctrl]-[shift]-v\fP  Paste selection."
.IP "\fB[ctrl]-[shift]-l\fP  Reset scrollback."
