.TH lwt 1 "2012-02-08" " " " "

\." === [ NAME ] ===============================================================
.SH NAME
lwt \- Lightweight terminal

\." === [ SYNOPSIS ] ===========================================================
.SH SYNOPSIS
.B lwt

\." === [ DESCRIPTION ] ========================================================
.SH DESCRIPTION
Lightweight
.B
GTK
and
.B
VTE
based terminal emulator.

\." === [ KEY BINDINGS ] =======================================================
.
.SH "KEY BINDINGS"
The default key bindings of
.B
VTE
are extended with the following:
.IP "\fB[ctrl]-[shift]-c\fP  Copy selection."
.IP "\fB[ctrl]-[shift]-v\fP  Paste selection."
.IP "\fB[ctrl]-[shift]-l\fP  Reset scrollback."
