.TH lwt 1 "2015-09-21" " " " "

\." === [ NAME ] ===============================================================
.SH NAME
lwt \- Lightweight terminal

\." === [ SYNOPSIS ] ===========================================================
.SH SYNOPSIS
.B lwt

\." === [ DESCRIPTION ] ========================================================
.SH DESCRIPTION
A lightweight terminal emulator based on
the
.B
GTK
and
.B
VTE
libraries.

\." === [ KEY BINDINGS ] =======================================================
.SH "KEY BINDINGS"
The default key bindings of VTE are extended with the following:
.IP "\fB[ctrl] + [shift] + 'c'\fP  Copy selection."
.IP "\fB[ctrl] + [shift] + 'v'\fP  Paste clipboard."
.IP "\fB[ctrl] + [shift] + 'l'\fP  Reset scrollback."
.IP "\fB[ctrl] + '+'\fP  Increase font size."
.IP "\fB[ctrl] + '-'\fP  Decrease font size."

\." === [ BUGS ] ===============================================================
.SH BUGS
It's too small and too cute.
